/** @type {import('tailwindcss').Config} */
export default {
    content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "surface-bright": "#363940",
                "secondary-container": "#00f1fd",
                "primary-fixed-dim": "#9bcbff",
                "on-secondary-fixed": "#002022",
                "on-secondary-container": "#006a6f",
                "inverse-surface": "#e0e2eb",
                "secondary-fixed-dim": "#00dce6",
                "on-primary-container": "#003e68",
                "on-surface-variant": "#bfc7d3",
                "on-error-container": "#ffdad6",
                "on-primary-fixed-variant": "#004a7a",
                "surface-container-low": "#181c22",
                "tertiary-fixed-dim": "#c6c6c7",
                outline: "#8a919c",
                primary: "#9bcbff",
                "inverse-primary": "#00629f",
                tertiary: "#c6c6c7",
                "on-error": "#690005",
                background: "#101419",
                "inverse-on-surface": "#2d3137",
                "on-primary-fixed": "#001d34",
                "tertiary-fixed": "#e2e2e2",
                "surface-container-high": "#262a31",
                "on-tertiary-fixed": "#1a1c1c",
                "on-primary": "#003256",
                "on-tertiary-fixed-variant": "#454747",
                "surface-dim": "#101419",
                "surface-variant": "#31353c",
                "error-container": "#93000a",
                "secondary-fixed": "#6ff6ff",
                "on-tertiary-container": "#3b3d3d",
                "on-tertiary": "#2f3131",
                "on-surface": "#e0e2eb",
                "surface-tint": "#9bcbff",
                error: "#ffb4ab",
                "primary-fixed": "#d0e4ff",
                "on-secondary-fixed-variant": "#004f53",
                surface: "#101419",
                "outline-variant": "#404751",
                "on-secondary": "#00373a",
                "primary-container": "#4facfe",
                "surface-container": "#1c2026",
                "tertiary-container": "#a6a7a7",
                secondary: "#dcfdff",
                "surface-container-lowest": "#0b0e14",
                "surface-container-highest": "#31353c",
                "on-background": "#e0e2eb"
            },
            borderRadius: { DEFAULT: "0.25rem", lg: "0.5rem", xl: "0.75rem", xxl: "2rem", "3xl": "32px", full: "9999px" },
            spacing: { "stack-sm": "0.5rem", "container-max": "1280px", gutter: "2rem", "section-gap": "4.5rem", "stack-md": "1.5rem", "margin-mobile": "1.25rem" },
            fontFamily: {
                "label-mono": ["Inter", "monospace"],
                "body-md": ["Inter", "sans-serif"],
                "headline-lg": ["Inter", "sans-serif"],
                "display-hero": ["Inter", "sans-serif"],
                "headline-md": ["Inter", "sans-serif"],
                "headline-lg-mobile": ["Inter", "sans-serif"],
                "body-lg": ["Inter", "sans-serif"]
            },
            fontSize: { "label-mono": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "500" }], "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }], "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }], "display-hero": ["72px", { lineHeight: "80px", letterSpacing: "-0.04em", fontWeight: "800" }], "headline-md": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }], "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }], "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }] }
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/container-queries'),
    ],
};
